#!/usr/bin/env Rscript
# ============================================================================
# 06_export_dashboard.R  —  dashboard handoff file (embeddable, no fetch needed)
# ----------------------------------------------------------------------------
# Inputs : outputs/lpi_scores_long.csv, outputs/lpi_weights_by_year.csv
# Output : outputs/dashboard/lpi_data.js   ->  defines window.LPI_DATA
#
# The dashboard HTML is opened via file:// and embeds all data as JS (no runtime
# fetch of local files is possible under file://). Include this once:
#     <script src="../model/model_LPI/outputs/dashboard/lpi_data.js"></script>
# then read window.LPI_DATA in the chart code. Regenerating the LPI never
# requires editing the (minified, ~1.3 MB) dashboard HTML.
# Run from: model/model_LPI/  (after 05)
# ============================================================================
suppressMessages(library(jsonlite))
sc <- read.csv("outputs/lpi_scores_long.csv", check.names=FALSE, stringsAsFactors=FALSE)
W  <- read.csv("outputs/lpi_weights_by_year.csv", stringsAsFactors=FALSE)

scores <- lapply(seq_len(nrow(sc)), function(i) list(
  year=sc$year[i], province=sc$province[i],
  pasar_kerja=sc$pasar_kerja_0_100[i], struktural=sc$struktural_0_100[i],
  tekanan=sc$tekanan_0_100[i], lpi=sc$lpi_0_100[i], lpi_raw=sc$lpi_raw[i],
  rank=sc$lpi_rank[i], tier=sc$tier[i], tier_label=sc$tier_label[i]))

weights <- setNames(lapply(seq_len(nrow(W)), function(i) list(
  N=W$N[i], pasar_kerja=W$Labour[i], struktural=W$Econ[i], tekanan=W$Pressure[i])),
  as.character(W$year))

payload <- list(
  meta = list(
    product = "Layoff Pressure Index (LPI)",
    method  = "PCA pillars + OECD/JRC factor-analysis weighting (Handbook 2008, 6.1)",
    scale   = "0-100, within-year min-max; higher = more layoff pressure",
    phk_role= "validation target only, never an input",
    years   = sort(unique(sc$year)),
    tiers   = c("Risiko Sangat Tinggi","Risiko Tinggi","Risiko Sedang","Risiko Rendah"),
    generated = as.character(Sys.Date())),
  weights = weights,
  scores  = scores)

dir.create("outputs/dashboard", showWarnings=FALSE, recursive=TRUE)
js <- paste0("/* Auto-generated by model_LPI/code/06_export_dashboard.R — do not edit by hand. */\n",
             "window.LPI_DATA = ",
             toJSON(payload, auto_unbox=TRUE, pretty=TRUE, digits=4), ";\n")
writeLines(js, "outputs/dashboard/lpi_data.js")
cat(sprintf("wrote outputs/dashboard/lpi_data.js  (%d province-year rows, %d years)\n",
            nrow(sc), length(unique(sc$year))))
