#!/usr/bin/env Rscript
# ============================================================================
# 08_score_monthly.R  —  monthly LPI using the frozen base-year calibration
# ----------------------------------------------------------------------------
# Produces a province x month LPI time series. Only the pressure (LEI) input
# moves; the structural pillars, standardisation, weights and 0-100 bounds are
# all held frozen at the base year (from 07_freeze_calibration.R). This makes
# scores comparable month to month. A month can score >100 or <0 if pressure
# moves beyond the base-year range (kept, not clamped — it is informative).
#
# Inputs : outputs/lpi_calibration_<BASE>.rds
#          ../model_LEI/data/Komposit_LEI_Ketenagakerjaan.xlsx (LEI Per Provinsi, monthly)
# Outputs: outputs/lpi_monthly.csv
#          outputs/dashboard/lpi_monthly.js   (window.LPI_MONTHLY)
# Self-check: feeding the base-year ANNUAL-MEAN LEI must reproduce the base-year
#            annual LPI (outputs/lpi_composite.rds s100). Fails loudly otherwise.
# Run from: model/model_LPI/   (after 07)
# ============================================================================
suppressMessages({library(readxl); library(jsonlite)})
BASE <- 2025L
cal  <- readRDS(sprintf("outputs/lpi_calibration_%d.rds", BASE))
LEIX <- "../model_LEI/data/Komposit_LEI_Ketenagakerjaan.xlsx"

# score one set of (province -> LEI value) with the frozen calibration
score <- function(prov, lei) {
  keep <- prov %in% cal$provinces
  prov <- prov[keep]; lei <- lei[keep]
  zL <- (cal$struct_labour[prov] - cal$mu[1]) / cal$sd[1]
  zE <- (cal$struct_econ[prov]   - cal$mu[2]) / cal$sd[2]
  zP <- (lei                     - cal$mu[3]) / cal$sd[3]
  comp <- cal$weights[1]*zL + cal$weights[2]*zE + cal$weights[3]*zP
  lpi  <- 100*(comp - cal$bounds["min"]) / (cal$bounds["max"] - cal$bounds["min"])
  data.frame(province=prov, zL=as.numeric(zL), zE=as.numeric(zE), zP=as.numeric(zP),
             comp=as.numeric(comp), lpi=as.numeric(lpi), row.names=NULL)
}

# ---- read monthly LEI ------------------------------------------------------
raw <- readxl::read_excel(LEIX, sheet="LEI Per Provinsi")
raw <- raw[!is.na(raw$Provinsi) & !is.na(raw$Tahun) & !is.na(raw$Bulan) &
           !is.na(raw$Indeks_LEI_Labour), ]

# ---- score every province-month -------------------------------------------
key <- paste(raw$Tahun, raw$Bulan)
parts <- lapply(split(seq_len(nrow(raw)), key), function(ix) {
  s <- score(raw$Provinsi[ix], raw$Indeks_LEI_Labour[ix])
  s$year <- as.integer(raw$Tahun[ix][1]); s$month <- as.integer(raw$Bulan[ix][1]); s
})
mon <- do.call(rbind, parts)
mon <- mon[order(mon$year, mon$month, -mon$lpi), ]
mon$lpi <- round(mon$lpi,1); mon$comp <- round(mon$comp,3)
mon <- mon[, c("year","month","province","lpi","comp","zL","zE","zP")]
for (c in c("zL","zE","zP")) mon[[c]] <- round(mon[[c]],3)
write.csv(mon, "outputs/lpi_monthly.csv", row.names=FALSE)

# ---- dashboard handoff (monthly time series) -------------------------------
series <- lapply(seq_len(nrow(mon)), function(i) list(
  year=mon$year[i], month=mon$month[i], province=mon$province[i], lpi=mon$lpi[i]))
js <- paste0("/* Auto-generated by model_LPI/code/08_score_monthly.R — do not edit. */\n",
             "window.LPI_MONTHLY = ",
             toJSON(list(meta=list(base_year=BASE,
               note="frozen base-year weights & structure; only pressure moves; 0-100 may exceed range",
               weights=list(pasar_kerja=round(100*cal$weights[1],1),
                            struktural=round(100*cal$weights[2],1),
                            tekanan=round(100*cal$weights[3],1))),
               series=series), auto_unbox=TRUE, pretty=TRUE, digits=3), ";\n")
dir.create("outputs/dashboard", showWarnings=FALSE, recursive=TRUE)
writeLines(js, "outputs/dashboard/lpi_monthly.js")

cat(sprintf("scored %d province-months across %d months (%d provinces)\n",
            nrow(mon), length(unique(paste(mon$year,mon$month))), length(cal$provinces)))

# ---- SELF-CHECK: annual-mean LEI must reproduce base-year annual LPI --------
b <- raw[raw$Tahun==BASE, ]
ann <- aggregate(Indeks_LEI_Labour ~ Provinsi, data=b, FUN=mean)
chk <- score(ann$Provinsi, ann$Indeks_LEI_Labour)
ref <- readRDS("outputs/lpi_composite.rds")$res[[as.character(BASE)]]$s100
m <- merge(chk, data.frame(province=names(ref), lpi_ref=as.numeric(ref)), by="province")
d <- max(abs(m$lpi - m$lpi_ref))
cat(sprintf("self-check vs %d annual LPI: matched %d/%d provinces, max abs diff = %.3g\n",
            BASE, nrow(m), length(ref), d))
if (nrow(m)==length(ref) && d < 1e-6) cat("OK — reproduces base-year annual LPI exactly.\n") else
  cat("WARNING — monthly machinery does not reproduce the annual LPI; inspect.\n")
